### PR TITLE
Dropdown Feature with props for List view

### PR DESCRIPTION
**Pull request by Manav958**
I have added the the dropdown feature in which the full scrollable list is restricted to 2 elements of the list and dropdown for the other methods
also for backward compatibility so that user can choose between full list view and the new feature i have added prop to  the custom tab view file for the same

### CODE REVIEW

**Comment by manideepk90** [comment]
can you use the theme styles from the Theme provided from user configuration which derives the theme from the native configuration object

**Comment by Manav958** [comment]
Sir,
Do you mean that the styles that I have written on the top of file
In styles module

I have to remove it and
Use ThemeBasedstyle.res file in the hooks folder to get the same styles?

**Comment by manideepk90** [comment]
https://github.com/juspay/hyperswitch/issues/6229

**Comment by Manav958** [comment]
Happy Diwali Everyone!!

Will the PR be accepted today as it is the last day for hacktoberfest?

**Review by manideepk90 — COMMENTED** [review]
Suggested improvements: 
1. This PR is not working in mobile. 
2. The container styles can be replaced by viewStyle and text styles can be replaced by textStyle. 
3. the dlist logic can be improved. 
4. list is not rendering properly.
5. rescript warning are listed.
6. virtualization issues with flatlist

**Pull request closed without merging**
